version: "3.7"

services:
  database:
    image: postgres:14-alpine
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-projectdb}
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data

  cacheStore:
    image: redis:6.2-alpine
    ports:
      - "6666:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:-redis-code-cache-password}"
    restart: always

  clickhouse:
    image: "clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-22.9.2-alpine}"
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - "./.docker/clickhouse/single_node/config.xml:/etc/clickhouse-server/config.xml"
      - "./.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml"

volumes:
  database-data:
